export const testData = {
  headings: [
    'ID', 'Name', 'Price', 'Stock', 'Category', 'Expiry Date', 'Manufacturer', 'Batch Number', 'Dosage', 'Type',
    'Prescription Required', 'Discount', 'Warehouse Location', 'Supplier', 'Storage Temp', 'Side Effects',
    'Approval Status', 'Reorder Level', 'Unit', 'Packaging', 'Barcode', 'Country of Origin', 'Manufacturing Date',
    'Last Restocked', 'Sales Volume', 'Patient Rating', 'Weight', 'Dimensions', 'Is OTC', 'Certification',
    'Supplier Contact', 'Reviews', 'Active Ingredient', 'Toxicity Level', 'Interactions', 'Refund Policy',
    'Insurance Coverage', 'Prescribed By', 'Order Frequency', 'Profit Margin', 'Regulatory Code',
    'Shipping Method', 'Tracking Number', 'Production Batch', 'Special Handling', 'Online Availability',
    'Marketing Status', 'Warranty', 'Notes'
  ],
  maincontent: [
    {
      id: { value: 1, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 2, error: false },
      name: { value: "", error: false },
      price: { value: -5, error: false },
      expiryDate: { value: "2023-12-01", error: false },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval Awaiting regulatory approval " },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 3, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 4, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 5, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 6, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: false },
      expiryDate: { value: "2023-12-01", error: false },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: false },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 7, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 8, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 9, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 10, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 11, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 12, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 13, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 14, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 15, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 16, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 17, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 18, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 19, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 20, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 21, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 22, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 23, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 24, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 25, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 26, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 27, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 28, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 29, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 30, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 31, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 32, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 33, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 34, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 35, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 36, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 37, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 38, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 39, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 40, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 41, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 42, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 43, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 44, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 45, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 46, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 47, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 48, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 49, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 50, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value:  51, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 52, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
    {
      id: { value: 53, error: false },
      name: { value: "Aspirin", error: false },
      price: { value: 10, error: false },
      stock: { value: 100, error: false },
      category: { value: "Medicine", error: false },
      expiryDate: { value: "2026-05-20", error: false },
      manufacturer: { value: "Pharma Corp", error: false },
      batchNumber: { value: "B001", error: false },
      dosage: { value: "500mg", error: false },
      type: { value: "Tablet", error: false },
      prescriptionRequired: { value: "Yes", error: false },
      discount: { value: 5, error: false },
      warehouseLocation: { value: "A1", error: false },
      supplier: { value: "MediSupplies", error: false },
      storageTemp: { value: "25°C", error: false },
      sideEffects: { value: "Nausea", error: false },
      approvalStatus: { value: "Approved", error: false },
      reorderLevel: { value: 50, error: false },
      unit: { value: "mg", error: false },
      packaging: { value: "Box of 20", error: false },
      barcode: { value: "1234567890", error: false },
      countryOfOrigin: { value: "USA", error: false },
      manufacturingDate: { value: "2024-01-15", error: false },
      lastRestocked: { value: "2025-03-10", error: false },
      salesVolume: { value: 500, error: false },
      patientRating: { value: 4.5, error: false },
      weight: { value: "50g", error: false },
      dimensions: { value: "10x5x3cm", error: false },
      isOTC: { value: "No", error: false },
      certification: { value: "FDA Approved", error: false },
      supplierContact: { value: "supplier@medisupplies.com", error: false },
      reviews: { value: 20, error: false },
      activeIngredient: { value: "Acetylsalicylic Acid", error: false },
      toxicityLevel: { value: "Low", error: false },
      interactions: { value: "Avoid alcohol", error: false },
      refundPolicy: { value: "30 days", error: false },
      insuranceCoverage: { value: "Yes", error: false },
      prescribedBy: { value: "Dr. Smith", error: false },
      orderFrequency: { value: "Monthly", error: false },
      profitMargin: { value: "20%", error: false },
      regulatoryCode: { value: "RX-12345", error: false },
      shippingMethod: { value: "Air Freight", error: false },
      trackingNumber: { value: "TRK123456", error: false },
      productionBatch: { value: "P12345", error: false },
      specialHandling: { value: "Keep dry", error: false },
      onlineAvailability: { value: "Yes", error: false },
      marketingStatus: { value: "Active", error: false },
      warranty: { value: "2 years", error: false },
      notes: { value: "Store in a cool place", error: false },
    },
    {
      id: { value: 54, error: false },
      name: { value: "", error: "Name is required" },
      price: { value: -5, error: "Price cannot be negative" },
      expiryDate: { value: "2023-12-01", error: "Product is expired" },
      manufacturer: { value: "HealthBoost Ltd.", error: false },
      approvalStatus: { value: "Pending", error: "Awaiting regulatory approval" },
      salesVolume: { value: 200, error: false },
      patientRating: { value: 3.8, error: false },
      supplierContact: { value: "info@naturecare.com", error: false },
    },
    {
      id: { value: 55, error: false },
      name: { value: "Paracetamol", error: false },
      price: { value: 15, error: false },
      expiryDate: { value: "2027-08-15", error: false },
      manufacturer: { value: "MediLife Pharmaceuticals", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "contact@quickmeds.com", error: false },
    },
    {
      id: { value: 56, error: false },
      name: { value: "Ibuprofen", error: false },
      price: { value: 8, error: false },
      expiryDate: { value: "2028-01-01", error: false },
      manufacturer: { value: "Pain Relief Pharma", error: false },
      approvalStatus: { value: "Approved", error: false },
      supplierContact: { value: "support@painrelief.com", error: false },
      weight: { value: "75g", error: false },
    },
  ],
};
