const categoriesData = [
  //   -------------------------------------   Medical Equipment and Devices  -------------------------------------
  {
    schema: "MedicalEquipmentAndDevices",
    name: "Medical Equipment and Devices",
    subCategories: [
      {
        name: "Diagnostic Tools",
        anotherCategories: ["Imaging Tools", "Blood Testing Tools", "Services"]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Imaging Equipment",
        anotherCategories: [
          "Radiography",
          "Ultrasound Systems",
          "Mammography Machines",
          "Fluoroscopy Machines",
          "Endoscopic Cameras",
          "3D Scanners",
          "Thermal Imaging Cameras",
          "Infrared Cameras",
          "MRI",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Surgical Instruments",
        anotherCategories: [
          "Scalpels",
          "Bone Saws",
          "Rongeurs",
          "Curettes",
          "Needle Holders",
          "Forceps (e.g., Thumb forceps, Tissue forceps, Allis forceps)",
          "Towel Clamps",
          "Hemostatic Clamps (e.g., Kelly, Mosquito, Crile clamps)",
          "Vascular Clamps",
          "Bulldog",
          "Surgical Sutures",
          "Surgical Staplers",
          "Ligating",
          "Endoscopes",
          "Laryngoscopes",
          "Otoscopes",
          "Proctoscopes",
          "Bone Chisels",
          "Bone Files",
          "Orthopedic Screws and Plates",
          "Intramedullary Nails",
          "Brain Retractors",
          "Craniotomes",
          "Penfield Dissectors",
          "Uterine Dilators",
          "Curettes (e.g., Sims Curette)",
          "Tenaculum",
          "Rib Spreaders",
          "Aortic Punches",
          "Vascular Clamps",
          "Skin Graft Knives",
          "Liposuction Cannulas",
          "Delicate Scissors and Forceps",
          "Surgical Trays",
          "Suction Tubes (e.g., Yankauer, Poole suction tips)",
          "Sponges and Sponge Forceps",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Monitoring Devices",
        anotherCategories: [
          "Cardiovascular Monitoring",
          "Electrocardiogram (ECG/EKG) Monitors",
          "Blood Pressure Monitors",
          "Pulse Oximeters",
          "Capnography Devices",
          "Spirometers",
          "Electroencephalogram (EEG) Monitors",
          "Intracranial Pressure Monitors",
          "Sleep Monitoring Devices",
          "Fetal Heart Rate Monitors",
          "Contraction Monitors",
          "Critical Care Monitoring",
          "ICU Bedside Monitors",
          "Multiparameter Monitors (e.g., vital signs)",
          "Infrared Thermometers",
          "Thermocouples",
          "Carbon Monoxide Detectors",
          "Air Quality Monitors",
          "Gas Leak Detectors",
          "Weather Stations",
          "Humidity and Temperature Sensors",
          "Network Traffic Monitors",
          "Server Monitoring Tools",
          "Endpoint Security Monitors",
          "Vehicle Diagnostic Monitors (OBD-II Scanners)",
          "Tire Pressure Monitoring Systems (TPMS)",
          "Dash Cameras with Monitoring Features",
          "Smart Home Monitoring Systems",
          "Baby Monitors",
          "Smart Thermostats",
          "Fitness Trackers",
          "Smartwatches",
          "Sleep Monitors",
          "CCTV Systems",
          "Alarm Monitoring Systems",
          "Access Control Monitors",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      // {
      //   name: "Monitoring Devices",
      //   anotherCategories: [
      //     "Scalpels",
      //     "Bone Saws",
      //     "Rongeurs",
      //     "Curettes",
      //     "Needle Holders",
      //     "Forceps (e.g., Thumb forceps, Tissue forceps, Allis forceps)",
      //     "Towel Clamps",
      //     "Hemostatic Clamps (e.g., Kelly, Mosquito, Crile clamps)",
      //     "Vascular Clamps",
      //     "Bulldog",
      //     "Surgical Sutures",
      //     "Surgical Staplers",
      //     "Ligating",
      //     "Endoscopes",
      //     "Laryngoscopes",
      //     "Otoscopes",
      //     "Proctoscopes",
      //     "Bone Chisels",
      //     "Bone Files",
      //     "Orthopedic Screws and Plates",
      //     "Intramedullary Nails",
      //     "Brain Retractors",
      //     "Craniotomes",
      //     "Penfield Dissectors",
      //     "Uterine Dilators",
      //     "Curettes (e.g., Sims Curette)",
      //     "Tenaculum",
      //     "Rib Spreaders",
      //     "Aortic Punches",
      //     "Vascular Clamps",
      //     "Skin Graft Knives",
      //     "Liposuction Cannulas",
      //     "Delicate Scissors and Forceps",
      //     "Surgical Trays",
      //     "Suction Tubes (e.g., Yankauer, Poole suction tips)",
      //     "Sponges and Sponge Forceps",
      //     "Services",
      //   ]
      //     ?.sort()
      //     ?.concat(["Other"]),
      // },
      {
        name: "Mobility Aids",
        anotherCategories: [
          "Manometers",
          "Pressure Transducers",
          "Standard Canes",
          "Quad Canes",
          "Folding Canes",
          "Underarm Crutches (Axillary Crutches)",
          "Forearm Crutches (Lofstrand Crutches)",
          "Platform Crutches",
          "Standard Walkers",
          "Rolling Walkers (Two-Wheel and Four-Wheel)",
          "Knee Walkers (Knee Scooters)",
          "Standard Wheelchairs",
          "Lightweight and Ultralight Models",
          "Bariatric Wheelchairs",
          "Power Wheelchairs",
          "Folding Electric Wheelchairs",
          "All-Terrain Wheelchairs",
          "3-Wheel Scooters",
          "4-Wheel Scooters",
          "Heavy-Duty Mobility Scooters",
          "Travel or Folding Mobility Scooters",
          "Stair Lifts (chair lifts for stairs)",
          "Platform Lifts",
          "Patient Transfer Hoists (e.g., Hoyer Lifts)",
          "Lower Limb Prosthetics (e.g., prosthetic legs)",
          "Upper Limb Prosthetics (e.g., prosthetic arms)",
          "Orthotic Braces (e.g., knee braces, ankle-foot orthoses)",
          "U-Step Walking Stabilizers",
          "Laser Walking Cues",
          "Knee Walkers",
          "Hip Chairs",
          "Pediatric Walkers",
          "Pediatric Wheelchairs",
          "Adaptive Strollers",
          "Shower Chairs",
          "Transfer Benches",
          "Raised Toilet Seats with Support Handles",
          "Vehicle Lifts (for wheelchairs or scooters)",
          "Hand Controls for Driving",
          "Swivel Seat Cushions",
          "Ramps (portable, threshold, or modular ramps)",
          "Grab Bars (for home or vehicle use)",
          "Anti-Slip Mats",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Respiratory Care",
        anotherCategories: [
          "Portable Oxygen Concentrators",
          "Stationary Oxygen Concentrators",
          "Oxygen Cylinders",
          "Mechanical Ventilators",
          "Invasive Ventilators",
          "Non-Invasive Ventilators (e.g., BiPAP, CPAP machines)",
          "Manual Resuscitators",
          "Ambu Bags (Bag-Valve-Mask)",
          "Endotracheal Tubes",
          "Tracheostomy Tubes",
          "Laryngeal Mask Airways (LMAs)",
          "Suction Devices",
          "Jet Nebulizers",
          "Ultrasonic Nebulizers",
          "Mesh Nebulizers",
          "Metered Dose Inhalers (MDI)",
          "Dry Powder Inhalers (DPI)",
          "Pulse Oximeters",
          "Capnography Devices (End-Tidal CO2 Monitors)",
          "Spirometers",
          "Peak Flow Meters",
          "Continuous Positive Airway Pressure (CPAP) Machines",
          "Bi-level Positive Airway Pressure (BiPAP) Machines",
          "Adaptive Servo-Ventilation (ASV) Devices",
          "Chest Percussion Vests (High-Frequency Chest Wall Oscillation)",
          "Positive Expiratory Pressure (PEP) Devices",
          "Vibratory PEP Devices (e.g., Acapella, Flutter Valve)",
          "Suction Catheters",
          "Cold Steam or Cool Mist Humidifiers",
          "Emergency Oxygen Kits",
          "Portable Suction Machines",
          "Rescue Breathing Devices",
          "Pediatric Nebulizers",
          "Pediatric Ventilators",
          "Pediatric Oxygen Masks and Cannulas",
          "Incentive Spirometers",
          "Breathing Trainers (e.g., PowerBreathe)",
          "Oxygen Masks and Nasal Cannulas",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Care Products",
        anotherCategories: [
          "Walkers and Rollators",
          "Canes and Quad Canes",
          "Wheelchairs (manual and electric)",
          "Mobility Scooters",
          "Transfer Aids (e.g., transfer boards, gait belts)",
          "Stair Lifts",
          "Dressing Aids (e.g., button hooks, zipper pulls)",
          "Eating and Drinking Aids (e.g., adaptive utensils, non-slip plates, spill-proof cups)",
          "Reachers and Grabbers",
          "Hearing Amplifiers and Aids",
          "Magnifying Glasses and Low-Vision Aids",
          "Shower Chairs and Stools",
          "Grab Bars and Safety Rails",
          "Raised Toilet Seats",
          "Non-Slip Mats",
          "Commode Chairs",
          "Bath Lifts",
          "Adjustable Beds",
          "Bed Rails",
          "Pressure Relief Mattresses and Cushions",
          "Overbed Tables",
          "Anti-Snore and Posture Pillows",
          "Blood Pressure Monitors",
          "Glucometers",
          "Thermometers",
          "Pulse Oximeters",
          "Fall Detection and Alert Systems",
          "Adult Diapers",
          "Incontinence Pads and Liners",
          "Waterproof Mattress Protectors",
          "Catheter Supplies",
          "Fall Alarms and Alert Systems",
          "Non-Slip Socks and Shoes",
          "Motion-Activated Lights",
          "Hip Protectors",
          "Hand Grips and Strengtheners",
          "Exercise Pedals (mini pedal exercisers)",
          "Resistance Bands",
          "Balance Training Aids",
          "Ramps (portable and fixed)",
          "Recliner Lift Chairs",
          "Easy-Grip Door Handles and Knobs",
          "Adaptive Kitchen Tools",
          "Electric Razors and Trimmers",
          "Long-Handled Brushes and Sponges",
          "Skin Care Products for Elderly Skin",
          "Nail Clippers for Thick Nails",
          "Amplified Telephones",
          "Large-Button Cell Phones",
          "Video Calling Devices (e.g., simplified tablets)",
          "Voice-Activated Assistants (e.g., Alexa, Google Home)",
          "Waste Disposal",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Pharmaceuticals  -------------------------------------
  {
    schema: "Pharmaceuticals",
    name: "Pharmaceuticals",
    subCategories: [
      {
        name: "Prescription Medications",
        anotherCategories: [
          "Antihypertensives",
          "Diuretics",
          "Antiarrhythmics",
          "Anticoagulants",
          "Antiplatelets",
          "Cholesterol-Lowering Drugs",
          "Antidepressants",
          "Antipsychotics",
          "Anxiolytics",
          "Sedatives",
          "Antiepileptics",
          "Stimulants",
          "Non-Opioid Analgesics",
          "Opioid Analgesics",
          "Adjuvant Pain Medications",
          "Hypothyroidism",
          "Insulin",
          "Oral Antidiabetics",
          "Hyperthyroidism",
          "Bronchodilators",
          "Inhaled Corticosteroids",
          "Antihistamines",
          "Leukotriene Receptor Antagonists",
          "Antifungal Drugs",
          "Immunotherapy",
          "Hormonal Therapy",
          "Vaccines",
          "Immunosuppressants",
          "Biologics",
          "Acne Medications",
          "Topical Steroids",
          "Antifungal Creams",
          "Psoriasis Treatments",
          "Antibiotic Eye Drops",
          "Eye Drops for Glaucoma",
          "Ear Drops",
          "Overactive Bladder Treatments",
          "Erectile Dysfunction Medications",
          "Laxatives",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Over-the-Counter Medications",
        anotherCategories: [
          "Acetaminophen (e.g., Tylenol)",
          "Nonsteroidal Anti-Inflammatory Drugs",
          "Ibuprofen",
          "Aspirin",
          "Naproxen",
          "Pseudoephedrine",
          "Pseudoephedrine",
          "Antihistamines",
          "Dextromethorphan",
          "Expectorants",
          "Combination Cold Medicines",
          "Antacids",
          "Calcium Carbonate",
          "Magnesium Hydroxide",
          "Ranitidine",
          "Proton Pump Inhibitors (PPIs)",
          "Laxatives",
          "Fiber Supplements",
          "Stimulant Laxatives",
          "Stool Softeners",
          "Osmotic Laxatives",
          "Antidiarrheals",
          "Anti-Nausea",
          "Topical Antibiotics",
          "Antifungal Creams and Powders",
          "Hydrocortisone Cream",
          "Sunburn Relief",
          "Acne Treatments",
          "Multivitamins",
          "Calcium",
          "Iron",
          "Magnesium",
          "Vitamin D",
          "Omega-3 Fatty Acids",
          "Probiotics",
          "Eye Drops",
          "Ear Drops",
          "Antiseptics",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Vaccines",
        anotherCategories: [
          "COVID-19 Vaccines",
          "nfluenza Vaccines",
          "epatitis A Vaccine",
          "epatitis B Vaccine",
          "uman Papillomavirus (HPV) Vaccine",
          "easles, Mumps, and Rubella (MMR) Vaccine",
          "aricella (Chickenpox) Vaccine",
          "otavirus Vaccine",
          "oster (Shingles) Vaccine",
          "olio Vaccine",
          "abies Vaccine",
          "neumococcal Vaccine (e.g., PCV13, PPSV23)",
          "etanus, Diphtheria, and Pertussis (Tdap) Vaccine",
          "eningococcal Vaccine (e.g., MenACWY, MenB)",
          "aemophilus Influenzae Type B (Hib) Vaccine",
          "yphoid Vaccine",
          "holera Vaccine",
          "TaP (Diphtheria, Tetanus, and Pertussis)",
          "MRV (Measles, Mumps, Rubella, and Varicella)",
          "epA-HepB (Twinrix)",
          "ontain killed pathogens (e.g., polio, hepatitis A)",
          "ontain weakened pathogens (e.g., MMR, varicella, yellow fever)",
          "RNA Vaccines",
          "ubunit, Recombinant, or Conjugate Vaccines",
          "iral Vector Vaccines",
          "oxoid Vaccines",
          "ediatric Vaccines",
          "dolescent Vaccines",
          "nfluenza",
          "ellow Fever",
          "yphoid",
          "apanese Encephalitis",
          "hingles (Shingrix)",
          "neumococcal (PCV13 or PPSV23)",
          "outine Vaccines",
          "ooster Vaccines",
          "atch-Up Vaccines",
          "bola Vaccine",
          "alaria Vaccine",
          "uberculosis (BCG) Vaccine",
          "SV (Respiratory Syncytial Virus) Vaccine",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Generic Drugs",
        anotherCategories: [
          "Antihypertensives",
          "Generic for ACE Inhibitors",
          "Generic for Beta-Blockers",
          "Generic for Calcium Channel Blockers",
          "Generic for Diuretics",
          "Generic for Atorvastatin (e.g., Lipitor)",
          "Generic for Simvastatin (e.g., Zocor)",
          "Generic for Rosuvastatin (e.g., Crestor)",
          "Generic for Warfarin (e.g., Coumadin)",
          "Generic for Clopidogrel (e.g., Plavix)",
          "Generic for Ibuprofen (e.g., Advil, Motrin)",
          "Generic for Naproxen (e.g., Aleve)",
          "Generic for Diclofenac (e.g., Voltaren)",
          "Generic for Oxycodone (e.g., OxyContin)",
          "Generic for Hydrocodone (e.g., Vicodin, Norco)",
          "Generic for Tramadol",
          "Generic for Tylenol (Paracetamol)",
          "Penicillins",
          "Cephalosporins",
          "Macrolides",
          "Fluoroquinolones",
          "Antifungals",
          "Oral Antidiabetics",
          "Insulin",
          "Antidepressants",
          "Antipsychotics",
          "Antianxiety Medications",
          "Antiepileptics",
          "Proton Pump Inhibitors (PPIs)",
          "H2 Blockers",
          "Antidiarrheals",
          "Laxatives",
          "Bronchodilators",
          "Corticosteroids",
          "Leukotriene Modifiers",
          "Topical Steroids",
          "Acne Treatments",
          "Antifungal Creams",
          "Oral Contraceptives",
          "Thyroid Medications",
          "Hormone Replacement Therapy",
          "Antihistamines",
          "Decongestants",
          "BPH Medications",
          "Erectile Dysfunction Medications",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Specialized Treatments",
        anotherCategories: [
          "Cancer Treatments",
          "Chemotherapy",
          "Traditional Chemotherapy",
          "Targeted Therapy",
          "Immunotherapy",
          "Hormone Therapy",
          "Radiation Therapy",
          "Stem Cell Transplantation",
          "Rare Disease Treatments",
          "Orphan Drugs",
          "Enzyme Replacement Therapy (ERT)",
          "Gene Therapy",
          "Immunoglobulin Therapy",
          "Neurodegenerative Diseases",
          "Parkinson's Disease",
          "Alzheimer's Disease",
          "Multiple Sclerosis",
          "Antiepileptic Drugs (AEDs)",
          "Vagus Nerve Stimulation (VNS)",
          "Deep Brain Stimulation (DBS)",
          "Thyroid Hormone Replacement Therapy",
          "Radioactive Iodine Therapy",
          "Insulin Therapy",
          "Continuous Glucose Monitoring (CGM)",
          "GLP-1 Receptor Agonists",
          "Heart Failure",
          "Beta-blockers",
          "ACE Inhibitors and ARBs",
          "Heart Transplantation",
          "Pacemakers",
          "Arrhythmias",
          "Ablation Therapy",
          "Autoimmune Disorders",
          "Disease-Modifying Antirheumatic Drugs (DMARDs)",
          "Immunosuppressive Therapy",
          "Monoclonal Antibodies",
          "Antiviral Treatments",
          "HIV/AIDS",
          "Hepatitis",
          "Systemic Fungal Infections",
          "New-generation Antibiotics",
          "Gene Editing",
          "Cell-Based Therapies",
          "Gabapentinoids",
          "Opioids",
          "Transcranial Magnetic Stimulation (TMS)",
          "Pain Pumps or Spinal Cord Stimulation",
          "Minimally Invasive Surgery (MIS)",
          "Organ Transplantation",
          "Arrhythmias",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Skin, Hair and Cosmetic Supplies  -------------------------------------
  {
    schema: "SkinHairCosmeticSupplies",
    name: "Skin, Hair and Cosmetic Supplies",
    subCategories: [
      {
        name: "Skin Care",
        anotherCategories: [
          "Facial Cleansers",
          "Foaming Cleansers",
          "Cream Cleansers",
          "Gel Cleansers",
          "Micellar Water",
          "Oil Cleansers",
          "Physical Exfoliants",
          "Scrubs",
          "Exfoliating Brushes/Tools",
          "Alpha Hydroxy Acids (AHAs)",
          "Beta Hydroxy Acids (BHAs)",
          "Enzyme Exfoliants",
          "Moisturizers",
          "Creams",
          "Lotions",
          "Gels",
          "Ointments",
          "Hyaluronic Acid Serums",
          "Peptide Serums",
          "Sunscreen Lotions",
          "Chemical Sunscreens",
          "Physical (Mineral) Sunscreens",
          "Tinted Sunscreens",
          "Quick and convenient sunscreen in spray form",
          "Retinoid Creams",
          "Retinol Serums",
          "Vitamin C Serums",
          "Peptides",
          "Firming Creams",
          "Salicylic Acid Cleansers",
          "Pimple Patches",
          "Acne Spot Treatments",
          "Fragrance-Free and Hypoallergenic Products",
          "Aloe Vera and Chamomile-Based Products",
          "Colloidal Oatmeal Creams",
          "Vitamin C and Niacinamide",
          "Alpha Arbutin",
          "Chemical Peels",
          "Hydrating, Firming, or Brightening Sheet Masks",
          "Detoxifying Masks",
          "Leave-On Treatment Masks",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Hair Care",
        anotherCategories: [
          "Daily Shampoos",
          "Clarifying Shampoos",
          "Dry Shampoo",
          "Color-Protecting Shampoos",
          "Volumizing Shampoos",
          "Moisturizing and Hydrating Shampoos",
          "Anti-Dandruff Shampoos",
          "Moisturizing Conditioners",
          "Volumizing Conditioners",
          "Color-Treated Hair Conditioners",
          "Smoothing and Anti-Frizz Conditioners",
          "Protein-Repair Masks",
          "Overnight Conditioners",
          "Shaping and Volumizing Mousse",
          "Styling Gels",
          "Texturizing Sprays",
          "Leave-In Conditioners",
          "Hair Serums",
          "Curl Creams",
          "Firm Hold Hairspray",
          "Flexible Hold Hairspray",
          "Shine Sprays",
          "Exfoliating Scalp Scrubs",
          "Scalp Balancing Shampoos",
          "Minoxidil",
          "Moisturizing and Nourishing Oils",
          "Scalp Oils",
          "Heat-Protectant Oils",
          "Anti-Frizz and Smoothing Serums",
          "Permanent Hair Dye",
          "Semi-Permanent Hair Dye",
          "Hydrating Hair Masks",
          "Color-Depositing Shampoos",
          "Color Protecting Shampoos and Conditioners",
          "Post-Color Treatment Masks",
          "Ceramic and Ionic Hair Dryers",
          "Flat Irons",
          "Curling Irons and Wands",
          "Detangling Brushes",
          "Round Brushes",
          "Hair Smoothing Treatments",
          "Chemical Hair Relaxers",
          "Perming Solutions",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Personal Hygiene",
        anotherCategories: [
          "Oral Hygiene",
          "Brushing teeth",
          "Flossing",
          "Mouthwash",
          "Dental checkups",
          "Regular showering or bathing",
          "Moisturizing",
          "Exfoliating",
          "Sun protection (sunscreen)",
          "Shampooing and conditioning",
          "Haircuts/trimming",
          "Scalp care (like treatments for dandruff)",
          "Hand washing with soap",
          "Hand sanitizing",
          "Nail care (trimming, cleaning)",
          "Regular washing",
          "Nail trimming",
          "Foot moisturization",
          "Proper footwear",
          "Washing and caring for the genital area",
          "Menstrual hygiene products",
          "Urinary hygiene (wiping front to back)",
          "Use of deodorants/antiperspirants",
          "Body sprays/perfumes",
          "Managing body odor",
          "Regular washing of clothes",
          "Keeping clothes clean and free of germs",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Baby Care",
        anotherCategories: [
          "Changing diapers regularly",
          "Diaper rash prevention and treatment",
          "Proper cleaning and wiping techniques",
          "Use of wipes, creams, and powders",
          "Breastfeeding or formula feeding",
          "Introducing solids (starting around 6 months)",
          "Bottle sterilization and feeding accessories",
          "Burping after feeding",
          "Regular baby baths",
          "Gentle baby shampoo and soap",
          "Nail care (trimming baby’s nails)",
          "Gentle skin moisturizing",
          "Safe sleep practices",
          "Creating a sleep-friendly environment",
          "Establishing sleep routines",
          "Monitoring baby’s sleep and waking patterns",
          "Regular pediatrician visits and vaccinations",
          "Monitoring for signs of illness or discomfort",
          "Baby-proofing the home",
          "Using safe baby gear (car seats, strollers, high chairs)",
          "Tummy time for muscle development",
          "Sensory play (textured toys, colorful objects)",
          "Talking and reading to encourage language development",
          "Encouraging mobility (crawling, standing, walking)",
          "Using teething rings and gels",
          "Cleaning baby’s gums and early teeth",
          "Signs of teething discomfort",
          "Dressing appropriately for the weather",
          "Soft, comfortable clothing that allows for easy movement",
          "Swaddling and sleep sacks for comfort and warmth",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Anti-aging Solutions",
        anotherCategories: [
          "Topical Anti-Aging",
          "Retinoids (retinol, tretinoin)",
          "Vitamin C serums",
          "Hyaluronic acid",
          "Peptides and growth factors",
          "Sunscreen (broad-spectrum SPF",
          "Eye creams for fine lines and puffiness",
          "Chemical exfoliants (AHAs, BHAs)",
          "Physical exfoliation (scrubs, brushes)",
          "Enzyme-based exfoliants",
          "Antioxidant-rich foods (fruits, vegetables, nuts)",
          "Omega-3 fatty acids for skin hydration",
          "Collagen-boosting foods (bone broth, fish, egg whites)",
          "Drinking adequate water",
          "Moisturizing from within",
          "Chemical peels",
          "Microneedling for collagen stimulation",
          "Laser treatments (Fractional, CO2, etc.)",
          "Laser skin resurfacing",
          "Botox (to reduce wrinkles)",
          "Proper hair cleansing and nourishment",
          "Collagen supplements",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Skin Graft",
        anotherCategories: [
          "Split-Thickness Skin Graft (STSG)",
          "Full-Thickness Skin Graft (FTSG)",
          "Composite Skin Graft",
          "Autograft",
          "Allograft",
          "Xenograft",
          "Synthetic Grafts",
          "Mesh Grafting",
          "Sheet Grafting",
          "Dermal Substitute Graft",
          "Graft Sizing and Shaping",
          "Harvesting",
          "Graft Meshing",
          "Wound Care",
          "Pain Management",
          "Physical Therapy/Scar Management",
          "Follow-up Monitoring",
          "Graft Rejection",
          "Infection",
          "Scarring",
          "Graft Failure",
          "Burn Reconstruction",
          "Facial Reconstruction",
          "Scar Revision",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Anti-Scar & Healing Ointments",
        anotherCategories: [
          "Silicone Gel Sheets or Silicone Creams",
          "Hydrocortisone Creams",
          "Vitamin E Ointments or Oils",
          "Honey-Based Ointments",
          "Onion Extract Gel (e.g., Mederma)",
          "Retinoid Creams (e.g., Tretinoin)",
          "Alpha Hydroxy Acids (AHAs) and Beta Hydroxy Acids (BHAs)",
          "Petroleum Jelly (e.g., Vaseline)",
          "Aloe Vera Gel",
          "Cocoa Butter or Shea Butter Creams",
          "Hydroquinone Creams",
          "Niacinamide Creams (Vitamin B3)",
          "Vitamin C Serums",
          "Keloid Scar Treatment Ointments",
          "Hypertrophic Scar Treatment Ointments",
          "Stretch Mark Ointments",
          "Tea Tree Oil",
          "Lavender Oil",
          "Calendula Ointments",
          "Silicone Gel Pads",
          "Pressure Garments",
          "Burn Ointments (e.g., Silver Sulfadiazine)",
          "Post-Surgical Scar Ointments",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Burn Care Solutions",
        anotherCategories: [
          "Cooling Gel or Creams",
          "Moisturizing Lotions or Creams",
          "Aloe Vera Gel",
          "Burn Relief Sprays (with Lidocaine)",
          "Cold Compress",
          "Neosporin or Bacitracin",
          "Hydrocolloid Dressings",
          "Burn Creams (with Silver Sulfadiazine)",
          "Blister Care",
          "Debridement",
          "Skin Grafts or Skin Substitutes",
          "Silver-Containing Dressings",
          "Acticoat or Aquacel Ag",
          "Biological or Synthetic Skin Dressings",
          "Pain Management (Opioids, Topical Anesthetics)",
          "Silicone Gel Sheets and Creams",
          "Pressure Garments",
          "Massage Therapy",
          "Scar Fading Creams (with Retinoids or Hydroquinone)",
          "Immediate Water Rinse",
          "Neutralizing Agents",
          "Antibiotic Ointments and Dressings",
          "Wound Care (Sterile Dressings)",
          "Monitoring for Internal Injuries",
          "Pain Relief and Wound Management",
          "Over-the-Counter Pain Relief",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Dermal Fillers & Injectables",
        anotherCategories: [
          "Hyaluronic Acid (HA) Fillers",
          "Juvederm",
          "Restylane",
          "Belotero",
          "Radiesse",
          "Sculptra",
          "Artefill",
          "Botox",
          "Dysport",
          "Xeomin",
          "Jeuveau",
          "Vampire Facial (PRP Facial)",
          "Fat grafting",
          "Voluma (Juvederm)",
          "Restylane Lyft",
          "Juvederm Volbella",
          "Restylane Silk",
          "Hyaluronic acid fillers",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Laser Treatment Devices",
        anotherCategories: [
          "CO2 Lasers (Carbon Dioxide)",
          "Lumenis UltraPulse",
          "Candela CO2RE",
          "Fractional CO2 Lasers",
          "Fraxel (Fractional CO2)",
          "Lumenis ResurFX",
          "Alexandrite Lasers (755 nm)",
          "Diode Lasers (800–810 nm)",
          "Lumenis LightSheer Duet",
          "Nd:YAG Lasers (1064 nm)",
          "Candela GentleYAG",
          "Q-Switched Nd:YAG Lasers",
          "Medlite C6 Q-Switched",
          "Radiofrequency Lasers (RF)",
          "Near Infrared Lasers (NIR)",
          "Blue Light Lasers (e.g., Acne Blue Light Therapy)",
          "Pulsed Dye Lasers (PDL)",
          "Pulsed Dye Lasers (PDL)",
          "PicoLasers",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Chemical Peels",
        anotherCategories: [
          "Alpha Hydroxy Acids (AHAs)",
          "Beta Hydroxy Acid (BHA)",
          "Salicylic acid",
          "Jessner's Solution",
          "TCA (Trichloroacetic Acid) - Low Concentration",
          "Trichloroacetic Acid (TCA)",
          "Jessner’s Solution (Stronger Formula)",
          "Glycolic Acid (High Concentrations)",
          "Phenol Peel",
          "TCA (High Concentrations 50–100%)",
          "Glycolic Acid Peels",
          "Salicylic Acid Peels",
          "Lactic Acid Peels",
          "Mandelic Acid Peels",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Vital Health and Wellness  -------------------------------------
  {
    schema: "VitalHealthAndWellness",
    name: "Vital Health and Wellness",
    subCategories: [
      {
        name: "Fitness Monitors",
        anotherCategories: [
          "Smartwatches",
          "Heart Rate Monitors",
          "Blood Oxygen Monitors",
          "Pedometers",
          "Calorie Counters",
          "Sleep Trackers",
          "ECG Wearables",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Herbal & Alternative Medicines",
        anotherCategories: [
          "Ayurvedic Herbs",
          "Homeopathic Remedies",
          "Traditional Chinese Medicine",
          "Herbal Teas",
          "Essential Oils",
          "Adaptogens",
          "Medicinal Mushrooms",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Immune Boosters",
        anotherCategories: [
          "Vitamin C Supplements",
          "Zinc Supplements",
          "Echinacea Extracts",
          "Elderberry Syrup",
          "Probiotics for Immunity",
          "Mushroom Immunity Blends",
          "Herbal Immunity Tonics",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Vitamins & Supplements",
        anotherCategories: [
          "Multivitamins",
          "Vitamin C",
          "Vitamin D",
          "Vitamin B Complex",
          "Vitamin B12",
          "Calcium Supplements",
          "Magnesium Supplements",
          "Omega-3 & Fish Oil",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Weight Management",
        anotherCategories: [
          "Fat Burners",
          "Meal Replacement Shakes",
          "Appetite Suppressants",
          "Keto Diet Supplements",
          "Detox Teas",
          "Metabolism Boosters",
          "Fiber Supplements",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Medical Consumables and Disposables  -------------------------------------
  {
    schema: "MedicalConsumablesAndDisposables",
    name: "Medical Consumables and Disposables",
    subCategories: [
      {
        name: "Bandages, Gauze, & Wound Dressings",
        anotherCategories: [
          "Adhesive Bandages",
          "Elastic Bandages",
          "Sterile Gauze",
          "Non-Adherent Dressings",
          "Hydrogel Dressings",
          "Foam Dressings",
          "Transparent Film Dressings",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Gloves, Masks, & Protective gear",
        anotherCategories: [
          "Surgical Gloves",
          "Nitrile Gloves",
          "Latex Gloves",
          "Disposable Face Masks",
          "N95 Masks",
          "Face Shields",
          "Protective Gowns",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Sterilization Products",
        anotherCategories: [
          "Autoclave Sterilization Bags",
          "Disinfectant Solutions",
          "Ethylene Oxide (ETO) Sterilizers",
          "UV Sterilization Devices",
          "Sterilization Pouches",
          "Indicator Strips",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Surgical Sutures & Adhesives",
        anotherCategories: [
          "Absorbable Sutures",
          "Non-Absorbable Sutures",
          "Skin Adhesives",
          "Surgical Staples",
          "Wound Closure Strips",
          "Tissue Sealants",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Syringes, IV Sets & Catheters",
        anotherCategories: [
          "Disposable Syringes",
          "Insulin Syringes",
          "IV Cannulas",
          "IV Administration Sets",
          "Foley Catheters",
          "Suction Catheters",
          "Urinary Catheters",
          "Absorbable Sutures",
          "Non-Absorbable Sutures",
          "Skin Adhesives",
          "Surgical Staples",
          "Wound Closure Strips",
          "Tissue Sealants",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Laboratory Supplies  -------------------------------------
  {
    schema: "LaboratorySupplies",
    name: "Laboratory Supplies",
    subCategories: [
      {
        name: "Test kits",
        anotherCategories: [
          "Blood Test Kits",
          "Urine Test Kits",
          "Pregnancy Test Kits",
          "COVID-19 Test Kits",
          "Drug Testing Kits",
          "Allergy Testing Kits",
          "Rapid Diagnostic Test Kits",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Microscopes & Lab Equipment",
        anotherCategories: [
          "Compound Microscopes",
          "Digital Microscopes",
          "Electron Microscopes",
          "Centrifuges",
          "Spectrophotometers",
          "Autoclaves",
          "pH Meters",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Chemicals & Reagents",
        anotherCategories: [
          "Laboratory Acids",
          "Laboratory Bases",
          "Staining Reagents",
          "Buffer Solutions",
          "Diagnostic Reagents",
          "Biochemical Reagents",
          "Cell Culture Reagents",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Lab Consumables",
        anotherCategories: [
          "Test Tubes",
          "Pipettes & Pipette Tips",
          "Petri Dishes",
          "Microplates",
          "Sample Containers",
          "Lab Gloves",
          "Centrifuge Tubes",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Diagnostic and Monitoring Devices  -------------------------------------
  {
    schema: "DiagnosticAndMonitoringDevices",
    name: "Diagnostic and Monitoring Devices",
    subCategories: [
      {
        name: "Blood Glucose Monitors",
        anotherCategories: [
          "Glucometers",
          "Test Strips",
          "Lancets",
          "Continuous Glucose Monitors",
          "Blood Sample Kits",
          "Glucose Control Solutions",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Blood Pressure Monitors",
        anotherCategories: [
          "Digital BP Monitors",
          "Manual BP Monitors",
          "Wrist BP Monitors",
          "Upper Arm BP Monitors",
          "Smart BP Monitors",
          "Cuffs & Accessories",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Oxygen Concentrators",
        anotherCategories: [
          "Portable Oxygen Concentrators",
          "Home Oxygen Concentrators",
          "High-Flow Oxygen Concentrators",
          "Oxygen Cylinders",
          "Oxygen Masks & Tubing",
          "Humidifier Bottles",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Wearable Health Devices",
        anotherCategories: [
          "Smartwatches",
          "Fitness Bands",
          "ECG Monitors",
          "Heart Rate Monitors",
          "Sleep Trackers",
          "Temperature Monitoring Devices",
          "Pulse Oximeters",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Hospital and Clinic Supplies  -------------------------------------
  {
    schema: "HospitalAndClinicSupplies",
    name: "Hospital and Clinic Supplies",
    subCategories: [
      {
        name: "Patient Beds & Stretchers",
        anotherCategories: [
          "Electric Hospital Beds",
          "Manual Hospital Beds",
          "ICU Beds",
          "Pediatric Beds",
          "Hydraulic Stretchers",
          "Transport Stretchers",
          "Bariatric Beds",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Trolleys & Storage Units",
        anotherCategories: [
          "Medication Trolleys",
          "Surgical Instrument Trolleys",
          "Linen Trolleys",
          "Emergency Crash Carts",
          "Utility Trolleys",
          "Bedside Lockers",
          "Storage Cabinets",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Examination Tables",
        anotherCategories: [
          "Adjustable Examination Tables",
          "Gynecological Examination Tables",
          "Pediatric Examination Tables",
          "Portable Examination Tables",
          "Hydraulic Examination Tables",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Medical Furniture",
        anotherCategories: [
          "Overbed Tables",
          "Stools & Chairs",
          "IV Stands",
          "Privacy Screens",
          "Instrument Stands",
          "Reclining Chairs",
          "Bedside Tables",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      // {
      //   name: "First Aid Kits",
      //   anotherCategories: [
      //     "Basic First Aid Kits",
      //     "Trauma First Aid Kits",
      //     "Travel First Aid Kits",
      //     "Workplace First Aid Kits",
      //     "Burn Care Kits",
      //     "Emergency Medical",
      //     "Services",
      //   ]
      //     ?.sort()
      //     ?.concat(["Other"]),
      // },
      // {
      //   name: "Emergency Medical Equipment",
      //   anotherCategories: [
      //     "Defibrillators",
      //     "Ventilators",
      //     "Suction Machines",
      //     "Emergency Resuscitation Kits",
      //     "Transport Ventilators",
      //     "Oxygen Supply Kits",
      //     "Services",
      //   ]
      //     ?.sort()
      //     ?.concat(["Other"]),
      // },
      // {
      //   name: "Trauma Care Products",
      //   anotherCategories: [
      //     "Trauma Bandages",
      //     "Hemostatic Dressings",
      //     "Cervical Collars",
      //     "Splints & Braces",
      //     "Trauma Stretchers",
      //     "Emergency Wound Care Kits",
      //     "Services",
      //   ]
      //     ?.sort()
      //     ?.concat(["Other"]),
      // },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Orthopedic Supplies  -------------------------------------
  {
    schema: "OrthopedicSupplies",
    name: "Orthopedic Supplies",
    subCategories: [
      {
        name: "Orthopedic Braces & Supports",
        anotherCategories: [
          "Knee Braces",
          "Ankle Braces",
          "Back Braces",
          "Elbow Braces",
          "Wrist Braces",
          "Shoulder Braces",
          "Hand & Finger Supports",
          "Neck Braces",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Splints & Casting Materials",
        anotherCategories: [
          "Arm Splints",
          "Leg Splints",
          "Finger Splints",
          "Soft Casts",
          "Hard Casts",
          "Fiberglass Casting",
          "Orthopedic Casting Tape",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Prosthetics",
        anotherCategories: [
          "Artificial Limbs",
          "Prosthetic Feet",
          "Prosthetic Hands",
          "Myoelectric Prosthetics",
          "Below-Knee Prostheses",
          "Above-Knee Prostheses",
          "Prosthetic Accessories",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Rehabilitation Equipment",
        anotherCategories: [
          "Exercise Equipment",
          "Resistance Bands",
          "Physical Therapy Equipment",
          "TENS Units",
          "Hot/Cold Therapy Devices",
          "Walking Aids",
          "Balance Trainers",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Dental Products  -------------------------------------
  {
    schema: "DentalProducts",
    name: "Dental Products",
    subCategories: [
      {
        name: "Dental Instruments & tools",
        anotherCategories: [
          "Scalers",
          "Probes",
          "Forceps",
          "Excavators",
          "Mirrors",
          "Surgical Instruments",
          "Crown and Bridge Instruments",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Orthodontic Supplies",
        anotherCategories: [
          "Braces",
          "Aligners",
          "Retainers",
          "Orthodontic Bands",
          "Orthodontic Wires",
          "Bracket Kits",
          "Orthodontic Wax",
          "Elastic Bands",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Dental Chairs and Accessories",
        anotherCategories: [
          "Dental Chairs",
          "Chair Covers",
          "Stool & Furniture",
          "Dental Lighting",
          "Headrests",
          "Armrests",
          "Patient Positioning Equipment",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Dental Consumables",
        anotherCategories: [
          "Dental Fillings",
          "Dental Crowns",
          "Dental Implants",
          "X-Ray Films",
          "Dental Cement",
          "Orthodontic Supplies",
          "Impression Materials",
          "Disposables",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Eye Care Supplies  -------------------------------------
  {
    schema: "EyeCareSupplies",
    name: "Eye Care Supplies",
    subCategories: [
      {
        name: "Contact Lenses and Solutions",
        anotherCategories: [
          "Soft Contact Lenses",
          "Hard Contact Lenses",
          "Toric Lenses",
          "Daily Disposable Lenses",
          "Extended-Wear Lenses",
          "Contact Lens Solution",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Eyewear",
        anotherCategories: [
          "Prescription Glasses",
          "Sunglasses",
          "Reading Glasses",
          "Sports Eyewear",
          "Blue Light Glasses",
          "Protective Eyewear",
          "Fashion Eyewear",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Eyewear Lenses",
        anotherCategories: [
          "Single Vision Lenses",
          "Bifocal Lenses",
          "Progressive Lenses",
          "Photochromic Lenses",
          "Polarized Lenses",
          "High Index Lenses",
          "Scratch-Resistant Lenses",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Eye Drops and Ointments",
        anotherCategories: [
          "Lubricating Eye Drops",
          "Allergy Eye Drops",
          "Redness-Relief Drops",
          "Prescription Eye Drops",
          "Antibacterial Ointments",
          "Steroid Eye Ointments",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Home Healthcare Products  -------------------------------------
  {
    schema: "HomeHealthcareProducts",
    name: "Home Healthcare Products",
    subCategories: [
      {
        name: "Mobility Aids",
        anotherCategories: [
          "Wheelchairs",
          "Walkers & Rollators",
          "Canes & Crutches",
          "Mobility Scooters",
          "Lift Chairs",
          "Stair Lifts",
          "Walking Frames",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Respiratory Care",
        anotherCategories: [
          "Nebulizers",
          "CPAP/BiPAP Machines",
          "Oxygen Concentrators",
          "Inhalers",
          "Pulse Oximeters",
          "Respiratory Masks",
          "Humidifiers",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Patient Monitoring Devices",
        anotherCategories: [
          "Blood Pressure Monitors",
          "Blood Glucose Monitors",
          "Pulse Oximeters",
          "ECG Monitors",
          "Smartwatches/Health Trackers",
          "Thermometers",
          "Wearable Health Monitors",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Care Products",
        anotherCategories: [
          "Adjustable Beds",
          "Bedside Commodes",
          "Walking Aids",
          "Fall Prevention Aids",
          "Bathing Aids",
          "Incontinence Products",
          "Pressure Relief Cushions",
          "Waste Disposal",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Alternative Medicines  -------------------------------------
  {
    schema: "AlternativeMedicines",
    name: "Alternative Medicines",
    subCategories: [
      {
        name: "Homeopathy",
        anotherCategories: [
          "Dilutions",
          "Tinctures",
          "Tablets",
          "Homeopathic Creams",
          "Homeopathic Gels",
          "Remedies for Colds",
          "Remedies for Skin conditions",
          "Remedies for Allergies",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Ayurvedic",
        anotherCategories: [
          "Herbal Supplements",
          "Ayurvedic Oils and Balms",
          "Wellness Products",
          "Hospital-Grade Disinfectants",
          "Multi-Surface Cleaners",
          "Antimicrobial Sprays",
          "Alcohol-Based Disinfectants",
          "Chlorine-Based Disinfectants",
          "Hydrogen Peroxide Disinfectants",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Disinfection and Hygiene Supplies  -------------------------------------
  {
    schema: "DisinfectionAndHygieneSupplies",
    name: "Disinfection and Hygiene Supplies",
    subCategories: [
      {
        name: "Hand Sanitizers",
        anotherCategories: [
          "Alcohol-Based Sanitizers",
          "Non-Alcoholic Hand Sanitizers",
          "Foaming Hand Sanitizers",
          "Gel-Based Sanitizers",
          "Antibacterial Hand Sprays",
          "Moisturizing Hand Sanitizers",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Air Purifiers",
        anotherCategories: [
          "UV-C Light Sterilizers",
          "HEPA Air Purifiers",
          "Activated Carbon Air Purifiers",
          "Ionic Air Purifiers",
          "Ozone Generators",
          "Smart Air Purifiers with App Control",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Cleaning Agents",
        anotherCategories: [
          "Medical-Grade Cleaning Solutions",
          "Floor & Equipment Cleaners",
          "Antibacterial Wipes",
          "Disinfectant Sprays",
          "Industrial Cleaning Solutions",
          "Biodegradable Cleaning Agents",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Nutrition and Dietary Products  -------------------------------------
  {
    schema: "NutritionAndDietaryProducts",
    name: "Nutrition and Dietary Products",
    subCategories: [
      {
        name: "Protein Powders and Shakes",
        anotherCategories: [
          "Whey Protein",
          "Plant-Based Protein",
          "Casein Protein",
          "Collagen Protein",
          "Egg Protein",
          "Soy Protein",
          "Pea Protein",
          "Hemp Protein",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Specialized Nutrition",
        anotherCategories: [
          "Clinical Nutrition",
          "Amino Acids",
          "Creatine",
          "Pediatric Nutrition",
          "Geriatric Nutrition",
          "Sports Nutrition",
          "High-Calorie Supplements",
          "Low-Carb Nutrition",
          "Medical Nutrition for Chronic Diseases",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Meal Replacement Solutions",
        anotherCategories: [
          "Nutritional Meal Bars",
          "Liquid Meal Replacements",
          "Keto Meal Replacements",
          "High-Protein Meal Replacements",
          "Fiber-Rich Meal Replacements",
          "Gluten-Free Meal Replacements",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Healthcare IT Solutions  -------------------------------------
  {
    schema: "HealthcareITSolutions",
    name: "Healthcare IT Solutions",
    subCategories: [
      {
        name: "Healthcare Management Software",
        anotherCategories: [
          "Hospital Information Systems",
          "Electronic Health Records",
          "Medical Billing Software",
          "Patient Scheduling Systems",
          "AI-Powered Health Analytics",
          "Inventory Management for Hospitals",
          "Insurance Claim Processing Software",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Telemedicine Platforms",
        anotherCategories: [
          "Virtual Healthcare Solutions",
          "Remote Consultation Platforms",
          "AI-Powered Diagnosis Systems",
          "Telepsychiatry Solutions",
          "Teletherapy & Rehabilitation Platforms",
          "Mobile Telemedicine Apps",
          "HIPAA-Compliant Video Conferencing Tools",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "IoT-Enabled Medical Devices",
        anotherCategories: [
          "Smart Healthcare Equipment",
          "Remote Patient Monitoring Devices",
          "AI-Integrated Medical Devices",
          "Wearable Health Sensors",
          "Smart ECG Monitors",
          "IoT-Connected Glucose Monitors",
          "Wireless Blood Pressure Monitors",
          "Cloud-Based Health Monitoring Solutions",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ]?.sort((a, b) => a?.name?.localeCompare(b?.name)),
  },
  //   -------------------------------------   Emergency and First Aid Supplies  -------------------------------------
  {
    schema: "EmergencyAndFirstAidSupplies",
    name: "Emergency and First Aid Supplies",
    subCategories: [
      {
        name: "First Aid Kits",
        anotherCategories: [
          "Basic First Aid Kits",
          "Trauma First Aid Kits",
          "Travel First Aid Kits",
          "Workplace First Aid Kits",
          "Burn Care Kits",
          "Emergency Medical",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Emergency Medical Equipment",
        anotherCategories: [
          "Defibrillators",
          "Ventilators",
          "Suction Machines",
          "Emergency Resuscitation Kits",
          "Transport Ventilators",
          "Oxygen Supply Kits",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
      {
        name: "Trauma Care Products",
        anotherCategories: [
          "Trauma Bandages",
          "Hemostatic Dressings",
          "Cervical Collars",
          "Splints & Braces",
          "Trauma Stretchers",
          "Emergency Wound Care Kits",
          "Services",
        ]
          ?.sort()
          ?.concat(["Other"]),
      },
    ],
  },
]?.sort((a, b) => a?.name?.localeCompare(b?.name));

const createCategory = (schema, name, subCategories) => ({
  schema,
  name,
  subCategories: subCategories.map((subCategory) => ({
    name: subCategory.name,
    anotherCategories: subCategory.anotherCategories,
  })),
});

const categoryArrays = categoriesData.map((category) =>
  createCategory(category.schema, category.name, category.subCategories)
);

export default categoryArrays;
